websites = {
    "kid_friendly": [
        "https://www.pbs.org/kids/",
        "https://kids.nationalgeographic.com/",
        "https://www.funbrain.com/",
        "https://www.coolmathgames.com/",
        "https://www.starfall.com/",
        "https://www.brainpop.com/",
        "https://www.kidsites.com/",
        "https://www.nick.com/",
        "https://www.sesamestreet.org/",
        "https://www.highlightskids.com/",
    ],
    "general": [
        "https://en.wikipedia.org/wiki/Main_Page",
        "https://www.bbc.com/",
        "https://www.cnn.com/",
        "https://www.reuters.com/",
        "https://www.nytimes.com/",
        "https://www.huffpost.com/",
        "https://www.theguardian.com/",
        "https://www.forbes.com/",
        "https://www.medium.com/",
        "https://www.quora.com/",
    ],
    "potentially_inappropriate": [
        "https://www.reddit.com/",
        "https://www.twitter.com/",
        "https://www.9gag.com/",
        "https://www.imgur.com/",
        "https://www.pornhub.com/",  # For identifying and blocking explicit content
        "https://www.onlyfans.com/",
        "https://www.tumblr.com/",
        "https://www.liveleak.com/",
        "https://www.worldstarhiphop.com/",
        "https://www.4chan.org/",
    ],
}
